---

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build and test ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make clean all

      - name: Unit Test
        run: make test

      - name: Assemble artifacts
        run: make install PREFIX= DESTDIR=${GITHUB_WORKSPACE}/dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: encval-${{ matrix.os }}-${{ matrix.arch }}-${{ github.sha }}
          path: dist

  smoke:
    name: Smoke tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: encval-linux-amd64-${{ github.sha }}

      - name: Setup environment
        run: |
          echo "LD_LIBRARY_PATH=${GITHUB_WORKSPACE}/dist/lib/encval" >> "$GITHUB_ENV"
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Show help
        run: encval --help

      - name: Run version subcommand
        run: encval version

