---

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {GOOS: linux, GOARCH: amd64}
          - {GOOS: linux, GOARCH: arm, GOARM: 6}
          - {GOOS: linux, GOARCH: arm64}
          - {GOOS: darwin, GOARCH: amd64}
          - {GOOS: darwin, GOARCH: arm64}
          - {GOOS: windows, GOARCH: amd64}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Setup build environment
        run: make ci-deps

      - name: Unit Test
        run: make test-all
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
          GOARM: ${{ matrix.GOARM }}

  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Setup build environment
        run: make ci-deps

      - name: Build all
        run: make dist GOBUILD_TAGS=crypto_plugins CGO_ENABLED=1

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: encval-dist
          path: "*.tgz"
          retention-days: 5

  smoke:
    name: Smoke tests
    runs-on: ubuntu-latest
    needs: [build]
    env:
      ENCVAL_HOME: /opt/encval
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: encval-dist

      - name: Setup environment
        run: make install-dist ci-env PREFIX=${ENCVAL_HOME}

      - name: Show help
        run: make -C test clean smoke

  compat:
    name: Compatibility tests
    runs-on: ubuntu-latest
    needs: [build]
    env:
      ENCVAL_HOME: /opt/encval
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: encval-dist

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install EYAML
        run: gem install hiera-eyaml

      - name: Setup environment
        run: make install-dist ci-env PREFIX=${ENCVAL_HOME}

      - name: Run EYAML compatibility tests
        run: make -C test clean eyaml-compat

      - name: Run ENCVAL compatibility tests
        run: make -C test clean encval-compat

