---

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {GOOS: linux, GOARCH: amd64}
          - {GOOS: linux, GOARCH: arm, GOARM: 6}
          - {GOOS: linux, GOARCH: arm64}
          - {GOOS: darwin, GOARCH: amd64}
          - {GOOS: darwin, GOARCH: arm64}
          - {GOOS: windows, GOARCH: amd64}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Unit Test
        run: make test-all
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
          GOARM: ${{ matrix.GOARM }}

  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Build all
        run: make all install-all PREFIX= DESTDIR=${GITHUB_WORKSPACE}/dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: encval-dist
          path: dist

  smoke:
    name: Smoke tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: encval-dist

      - name: Setup environment
        run: |
          echo "LD_LIBRARY_PATH=${GITHUB_WORKSPACE}/dist/lib/encval" >> "$GITHUB_ENV"
          echo "${GITHUB_WORKSPACE}/dist/bin" >> $GITHUB_PATH

      - name: Show help
        run: encval --help

      - name: Run version subcommand
        run: encval version

  compat:
    name: Compatibility tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: encval-linux-amd64-${{ github.sha }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install EYAML
        run: gem install hiera-eyaml

      - name: Setup environment
        run:  echo "${GITHUB_WORKSPACE}/dist/bin" >> $GITHUB_PATH

      - name: Run EYAML compatibility tests
        run: make -C test clean eyaml-compat

      - name: Run ENCVAL compatibility tests
        run: make -C test clean encval-compat

